version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: timetrap-app
    volumes:
      - ./backend:/var/www/html
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
    ports:
      - "9000:9000" # PHP-FPM for nginx
    depends_on:
      - postgres
      - redis
    environment:
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1

  nginx:
    image: nginx:alpine
    container_name: timetrap-nginx
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  postgres:
    image: postgres:15
    container_name: timetrap-postgres
    environment:
      POSTGRES_DB: timetrap_db
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: timetrap-redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
