version: "3.8"

services:
  app:
    build:
      context: ./docker/php
    container_name: timetrap-app
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    ports:
      - "9000:9000" #php-FPM port for NginX
    depends_on:
      - postgres
      - redis
    networks:
      - timetrap

  nginx:
    image: nginx:alpine
    container_name: timetrap-nginx
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - timetrap

  postgres:
    image: postgres:15
    container_name: timetrap-postgres
    restart: always
    environment:
      POSTGRES_DB: timetrap
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - timetrap

  redis:
    image: redis:alpine
    container_name: timetrap-redis
    ports:
      - "6379:6379"
    networks:
      - timetrap

networks:
  timetrap:
    driver: bridge

volumes:
  pgdata:
